---
- stat: path=/etc/php/{{ php_version }}/fpm/php.ini
  register: phpfpm

- stat: path=/etc/php/{{ php_version }}/cli/php.ini
  register: phpcli

- include: php-fpm-config.yml
  when: phpfpm.stat.exists

- include: php-cli-config.yml
  when: phpcli.stat.exists
