---
# We do not add ppa because we are not in debian but in raspbian and ppa ondrej/php does not seem to be supported
# - name: Add PPA Repository
#   become: yes
#   become_method: sudo
#   apt_repository: repo={{ php_ppa }}

# - name: Apt update
#   become: yes
#   become_method: sudo
#   apt: update_cache=yes

- name: Install PHP
  become: yes
  apt: name=php{{ php_version }} state=latest

- name: Install PHP Packages
  become: yes
  become_method: sudo
  apt: name={{ item }} state=latest
  with_items: "{{ php_packages }}"
  when: php_packages is defined
  notify:
    - restart php-fpm

- name: Start and enable php-fpm
  become: yes
  become_method: sudo
  service: name=php{{ php_version }}-fpm state=started enabled=yes

  # Configuration
- name: Php FPM and CLI configuration
  become: yes
  become_method: sudo
  include: configuration.yml
