---
- name: Set up a raspberry pi to host php web apps
  hosts: web
  remote_user: pi
  vars:
    user: pi
    php_version: "7.0"
    # domains: #now defined in group
    # - laravel.work
    #- other.work

  roles:
    - utils
    - nginx
    - php-fpm
    - mariadb

- name: Edit local hosts file for the domain to work
  hosts: localhost

  roles:
    - local
...
