---
- name: Install a pi web with nginx mariadb php-fpm and utils like
  hosts: web
  remote_user: pi
  vars:
    user: pi
    domains: l
    - laravel.work
    #- other.work

  roles:
    - utils
    - nginx
...
