---
- name: Install a pi web with nginx mariadb php-fpm and utils like
  hosts: web
  remote_user: pi
  vars:
    user: pi
    domains:
    - laravel.work
    #- other.work

  roles:
    - utils
    - nginx

- name: Edit local hosts file for the domain to work
  hosts: 127.0.0.1
  connection: local
  tasks:
  - name: Editing local hosts file to go to server (we'll see to use the dns to register the domain later)
    become: yes
    become_method: sudo
    # ansible_sbecome_pass: Samoht07 # launching with : ansible-playbook -i hosts playbook.yml --ask-become-pass
    lineinfile: path="/etc/hosts" line="{{ hostvars['piweb'].ansible_host }}\tlaravel.work"
    # with_items: "{{ domains }}"
      # path: /etc/hosts
      #regexp: '^127\.0\.0\.1'
      # line: '127.0.0.1 localhost'
      # owner: root
      # group: root
      # mode: 0644
...
