---
- name: Install a pi web with nginx mariadb php-fpm and utils like
  hosts: web
  remote_user: pi
  vars:
    user: pi
    # domains:
    # - laravel.work
    #- other.work

  roles:
    - utils
    - nginx

- name: Edit local hosts file for the domain to work
  hosts: localhost

  roles:
    - local
...
