---
- name: Set up a raspberry pi to host php web apps
  hosts: web
  remote_user: pi
  # vars:
    # user: pi #All vars moved to group_vars/all
    # php_version: "7.0" #now defined in group_vars
    # domains: #now defined in group_vars
    # - laravel.work
    #- other.work

  roles:
    - utils
    - nginx
    - php-fpm
    - mariadb
    - composer

  tasks:
    - name: Restart nginx
      become: yes
      become_method: sudo
      command: systemctl restart nginx.service

    - name: Restart php-fpm
      become: yes
      become_method: sudo
      command: systemctl restart php{{ php_version }}-fpm.service

    # - name: Restart mariadb
    #   become: yes
    #   become_method: sudo
    #   command: systemctl restart mariadb

- name: Edit local hosts file for the domain to work
  hosts: localhost

  roles:
    - local
...
