- name: Editing local hosts file to go to server (we'll see to use the dns to register the domain later)
  become: yes
  become_method: sudo
  lineinfile: path="/etc/hosts" line="{{ hostvars['piweb'].ansible_host }}\t{{ item }}"
  with_items: "{{ domains }}"
    # path: /etc/hosts
    #regexp: '^127\.0\.0\.1'
    # line: '127.0.0.1 localhost'
    # owner: root
    # group: root
    # mode: 0644
