#create username and new password
- name:  Create db user
  become: yes
  become_method: sudo
  mysql_user:
    name: "{{mariadb_username}}"
    password: "{{mariadb_password}}"
    priv: '*.*:ALL'
    state: present

- name:  Create APP database
  mysql_db:
    login_user: "{{mariadb_username}}"
    login_password: "{{mariadb_password}}"
    name: "{{mariadb_database_name}}"
    state: present
