---
# Later maybe add repositories if possible to have the latest version (https://downloads.mariadb.org/mariadb/repositories/#mirror=ovh)
# - name: Add PPA Repository
#   become: yes
#   become_method: sudo
#   apt_repository: repo={{ mariadb_ppa }}

# - name: Apt update
#   become: yes
#   become_method: sudo
#   apt: update_cache=yes

- name: Install MariaDB
  become: yes
  become_method: sudo
  apt: name=mariadb-server state=latest

#DONE DURING INSTALL IF NOT RETRY IT see https://wiki.archlinux.fr/MariaDB
# - name: Initializes the MariaDB data directory and creates the system and help tables, if they do not exist.
#   become: yes
#   become_method: sudo
#   shell: mysql_install_db --user=mysql --basedir=/usr --datadir=/var/lib/mysql

- name: Start and enable mariadb
  become: yes
  become_method: sudo
  service: name=mariadb state=started enabled=yes

  #Install MySQLdb Python package for ansible to be able to run queries ansible is python
- name: Adds Python MySQL support on Debian/Ubuntu
  become: yes
  become_method: sudo
  apt: name=python-mysqldb state=latest
  when: ansible_os_family == 'Debian'

  # Configuration secure installation
  # Reproducing sudo mysql_secure_installation
  # See https://stackoverflow.com/questions/25136498/ansible-answers-to-mysql-secure-installation

# /!\ ------- mysql_secure_installation IS NOT POSSIBLE BECAUSE WE GET MariaDB version 10.1 and 'ALTER USER' is in 10.2 ------- /!\
# see https://mariadb.com/kb/en/library/alter-user/
#ALTER USER
#MariaDB starting with 10.2.0
#The ALTER USER statement was introduced in MariaDB 10.2.0.

#Isolating mysql_secure_installation steps in seprate file mysql-secure-installation.yml so we can test it later when we get 10.2 version
# - name: Running same steps as mysql_secure_installation
#   include: mysql-secure-installation.yml

- name: Create user and initialize app database
  include: db-config.yml

- name: Reload privilege tables (FLUSH PRIVILEGES)
  command: 'mariadb -u {{ mariadb_username }} -p{{ mariadb_password }} -ne "{{ item }}"'
  with_items:
    - FLUSH PRIVILEGES
  changed_when: False

# - name: Import existing dump if needed
#   include: import-dump.yml
