---
#Can be overidden in a /vars/main.yml file in role or in /host_vars /group_vars or directly in vars section of playbook
php_ppa: "ppa:ondrej/php"
php_version: "7.0"
php_packages:
  - php{{ php_version }}-common
  - php{{ php_version }}-cli
  - php{{ php_version }}-intl
  - php{{ php_version }}-imagick
  - php{{ php_version }}-imap
  - php{{ php_version }}-curl
  - php{{ php_version }}-cgi
  - php{{ php_version }}-fpm
  - php{{ php_version }}-mysql
  - php{{ php_version }}-gd
  - php{{ php_version }}-mbstring
  - php{{ php_version }}-mcrypt
  - php{{ php_version }}-memcached
  - php{{ php_version }}-apcu
  - php{{ php_version }}-json
  - php{{ php_version }}-xml
  - php{{ php_version }}-zip

php_timezone: Europe/Paris
php_upload_max_filesize: "20M"
php_post_max_size: "20M"
php_memory_limit: "1024M"
php_max_execution_time: 60

php_opcache_enable: 1
php_opcache_revalidate_freq: 2592000
php_opcache_opcache_validate_timestamps: 1
php_opcache_max_accelerated_files: 20000
php_opcache_memory_consumption: 192
php_opcache_interned_strings_buffer: 16
php_opcache_fast_shutdown: 1

