---
- name: Checking if composer is already installed
  stat: path=/usr/bin/composer
  register: composer

- name: Getting composer installer
  shell: php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
  when: not composer.stat.exists

- name: Checking composer installer authenticity
  shell: php -r "if (hash_file('sha384', 'composer-setup.php') === '48e3236262b34d30969dca3c37281b3b4bbe3221bda826ac6a9a62d6444cdb0dcd0615698a5cbe587c3f0fe57a54d8f5') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
  when: not composer.stat.exists

- name: Running composer installer
  # become: yes
  # become_method: sudo
  shell: php composer-setup.php #--install-dir=/usr/bin
  # args:
  #   chdir: /usr/bin/
  when: not composer.stat.exists

- name: Deleting composer installer
  shell: php -r "unlink('composer-setup.php');"
  # args:
  #   chdir: /usr/bin/
  when: not composer.stat.exists

# - name: example copying file with owner and permissions
#   copy:
#     src: /home/{{ user }}/composer
#     dest: /etc/foo.conf
#     owner: foo
#     group: foo
#     mode: 0644
#   when: not composer.stat.exists
