---
- name: install git
  become: yes
  become_method: sudo
  apt: name=git state=latest

- name: install zsh
  become: yes
  become_method: sudo
  apt: name=zsh state=latest

- name: Change the default shell of user pi to zsh
  become: yes
  become_method: sudo
  user:
    name: pi
    shell: /usr/bin/zsh
