---
- name: install git
  become: yes
  become_method: sudo
  apt: name=git state=latest
  register: git

- name: install zsh
  become: yes
  become_method: sudo
  apt: name=zsh state=latest
  register: zsh

- name: Change the default shell of user pi to zsh
  become: yes
  become_method: sudo
  user:
    name: pi
    shell: /usr/bin/zsh
  when: zsh is succeeded and git is succeeded

#Install oh my zsh
- name: Backing up existing ~/.zshrc
  shell: if [ -f ~/.zshrc ]; then mv ~/.zshrc ~/.zshrc.orig; fi
  when: zsh is succeeded and git is succeeded
  # sudo: no

- name: Cloning  oh-my-zsh
  git:
    repo=https://github.com/robbyrussell/oh-my-zsh
    dest=~/.oh-my-zsh
  when: zsh is succeeded and git is succeeded
  register: cloning
  # sudo: no

- name: Creating new ~/.zshrc
  copy:
    src=~/.oh-my-zsh/templates/zshrc.zsh-template
    dest=~/.zshrc
  when: cloning is succeeded
  # sudo: no
